- hosts: devvm
  become: true
  roles:
  - python
  - docker
  - docker-compose
  tasks:
  - name: create git dir
    file:
      state: directory
      path: /home/agray/animal-noises
  - name: clone repo
    git:
      repo: https://github.com/agray998/animal-noises-demo
      dest: /home/agray/animal-noises
      clone: yes
  vars:
    docker_user: agray

- hosts: ciservers
  become: true
  roles:
  - python
  - docker
  - docker-compose
  - jenkins
  vars:
    docker_user: jenkins

- hosts: swarmmanagers
  become: true
  roles:
  - docker
  - swarm-manager
  tasks:
  - name: add ansible user to docker group
    user:
      name: agray
      groups: docker
      append: yes
  vars:
    docker_user: jenkins

- hosts: swarmworkers
  become: true
  roles:
  - docker
  - swarm-worker
  vars:
    docker_user: agray